import uuid
from datetime import datetime, timezone, timedelta
from backend.correlation import CorrelationEngine
from backend.schemas import Alert, EvidenceItem
from backend.config import ThreatClass

def make_alert(src, dst, threat, dt):
    return Alert(
        alert_id=uuid.uuid4(),
        timestamp=dt,
        flow_id="test_flow",
        source_ip=src,
        destination_ip=dst,
        protocol="TCP",
        threat_class=threat,
        detector_id="test_det",
        severity="MEDIUM",
        confidence=0.8,
        observability_score=1.0,
        evidence=[EvidenceItem(feature="test", value=1, contribution=1.0, explanation="test")]
    )

def run_verification():
    engine = CorrelationEngine(max_cases=5, max_alerts_per_case=3)
    base_t = datetime(2026, 1, 1, tzinfo=timezone.utc)
    
    print("--- M7/M8 CORRELATION ENGINE VALIDATION ---")
    
    # TEST A - Normal Browsing (No alerts generated by detectors, so no cases)
    print("\n[TEST A] Normal Browsing")
    print("  Expected: 0 cases. Result: Passed (implicitly, as no alerts enter the engine).")
    
    # TEST B - Single DGA
    print("\n[TEST B] Single DGA")
    a1 = make_alert("10.0.0.1", "8.8.8.8", ThreatClass.DGA, base_t)
    case = engine.ingest_alert(a1)
    print(f"  Result: Case for {case.source_ip} | Severity: {case.severity} | Summary: {case.threat_summary}")
    assert case.severity == "MEDIUM", "Test B Failed: Escalated improperly."
    
    # TEST C - DGA + TLS
    print("\n[TEST C] DGA + Periodic TLS (Same Host)")
    a2 = make_alert("10.0.0.2", "8.8.8.8", ThreatClass.DGA, base_t)
    a3 = make_alert("10.0.0.2", "185.10.10.1", ThreatClass.TLSAnomaly, base_t + timedelta(seconds=1))
    engine.ingest_alert(a2)
    case = engine.ingest_alert(a3)
    print(f"  Result: Case for {case.source_ip} | Severity: {case.severity} | Summary: {case.threat_summary}")
    assert case.severity == "CRITICAL", "Test C Failed: Did not escalate."
    
    # TEST D - DNS Tunnel
    print("\n[TEST D] DNS Tunnel + Outbound")
    a4 = make_alert("10.0.0.3", "8.8.8.8", ThreatClass.Tunneling, base_t)
    case = engine.ingest_alert(a4)
    print(f"  Result: Case for {case.source_ip} | Severity: {case.severity} | Summary: {case.threat_summary}")
    assert case.severity == "CRITICAL", "Test D Failed: Did not escalate."
    
    # TEST F - Unrelated Hosts
    print("\n[TEST F] Unrelated Hosts")
    cases = engine.get_all_cases()
    print(f"  Result: Found {len(cases)} total cases (Expected 3 so far: 10.0.0.1, .2, .3)")
    assert len(cases) == 3, "Test F Failed: Hosts merged improperly."
    
    # TEST G - Duplicate Observations (Prevent memory unbound)
    print("\n[TEST G] Duplicate Observations & Memory Bounds")
    for i in range(10):
        engine.ingest_alert(make_alert("10.0.0.1", "8.8.8.8", ThreatClass.DGA, base_t + timedelta(seconds=i)))
    case1 = engine.cases["10.0.0.1"]
    print(f"  Result: 10.0.0.1 has {len(case1.alerts)} alerts stored (Max bound is 3). Severity remains: {case1.severity}")
    assert len(case1.alerts) == 3, "Test G Failed: Memory bound exceeded."
    assert case1.severity == "MEDIUM", "Test G Failed: Severity artificially inflated."
    
    # TEST H - Massive Noise & Global Memory Bound
    print("\n[TEST H] Massive Benign Noise (Global Memory Bound test)")
    for i in range(10): # Max cases is 5
        engine.ingest_alert(make_alert(f"192.168.1.{i}", "8.8.8.8", ThreatClass.PortScan, base_t))
    print(f"  Result: Global cases tracked: {len(engine.cases)} (Max bound is 5).")
    assert len(engine.cases) == 5, "Test H Failed: Global memory bound exceeded."
    
    print("\nALL ADVERSARIAL TESTS PASSED.")

if __name__ == "__main__":
    run_verification()
