import os

BASE_DIR = r"E:\cyberos-prototype\cyberos-docs"

def write_file(path, content):
    with open(os.path.join(BASE_DIR, path), "w", encoding="utf-8") as f:
        f.write(content.strip())

def build_part3():
    # 04 Intelligence
    write_file("docs/04_intelligence/deterministic.md", """
# Deterministic Detection

## Why Rules Exist
Machine Learning is powerful, but probabilistic. Deterministic rules are explicit thresholds that catch known behaviors with 100% certainty (like a Slowloris signature or a massive byte exfiltration).

## Our Detectors
1. `ddos_stat_v1`: Volumetric attacks.
2. `beacon_stateful_v2`: Periodic C2.
3. `dga_lexical_v1`: High entropy DNS.
4. `dns_tunnel_stateful_v1`: DNS data transport.
5. `tls_behavioral_v1`: TLS anomalies.
6. `scan_v2`: High fan-out recon.
7. `exfil_v1`: Byte asymmetry.
8. `slow_http_v1`: Connection trickle exhaustion.
    """)

    write_file("docs/04_intelligence/ml_from_zero.md", """
# Machine Learning from Zero

## What is ML?
Machine Learning allows a system to learn patterns from data rather than being explicitly programmed with `if/then` rules.

## The Pipeline
1. **Features**: Measurable properties of the network (e.g., `packet_size_mean`).
2. **Labels**: The known truth (e.g., `1` for Malicious, `0` for Benign).
3. **Training**: The algorithm studies the features and labels to build a model.
4. **Validation**: Testing the model on data it has never seen to prevent *overfitting*.
    """)

    write_file("docs/04_intelligence/xgboost.md", """
# Why XGBoost?

## Tabular Data Supremacy
Network flow metadata is highly structured tabular data. Deep Learning (like Neural Networks) excels at unstructured data (images, text). For tabular data, **Gradient Boosted Decision Trees** (like XGBoost) consistently outperform Deep Learning in speed, accuracy, and explainability.

## V5 Model Architecture
* **Algorithm**: XGBoost (`xgb_window_v5`)
* **Precision**: 98.6876%
* **Recall**: 100%
* **F1**: 99.3394%
* **Inference Latency**: ~1.40 ms P50
    """)

    write_file("docs/04_intelligence/v4_to_v5_case_study.md", """
# V4 to V5 Case Study: A Failure in Semantics

> **A model is only as valid as the representation shared by training and production.**

## The V4 Failure
Our V4 XGBoost model achieved 99% accuracy offline. But when deployed to the production stream, it failed completely. Why?

The training dataset was generated using Python's `Scapy`. Production telemetry was generated by `Zeek`.

* **Scapy** counted L2 Ethernet frames (`byte_count = 13600`).
* **Zeek** counted L3 IP payloads (`byte_count = 1500`).

## The Investigation & Fix (V5)
We discovered the mismatch and created the `CanonicalObservation` schema. 
V5 was retrained using **Zeek-derived training vectors**. This ensured perfect parity between the training representation and the production data path.
    """)

    write_file("docs/04_intelligence/evidence_fusion.md", """
# Evidence Fusion

```mermaid
flowchart LR
    A[NetworkObservation] --> B[Rules]
    A --> C[XGBoost]
    B --> D[Fusion Engine]
    C --> D
    D --> E[SecurityCase]
```

## Why Fusion?
A single anomaly detection model will inevitably trigger False Positives. Our **Fusion Engine** demands cross-validation. An XGBoost alert will not become a severe Security Case unless deterministic logic provides contextual evidence (e.g., high probability + high exfiltration ratio).
    """)

    # 05 Architecture
    write_file("docs/05_architecture/streaming.md", """
# Streaming Architecture

## Redpanda (Kafka)
In a 10Gbps enterprise environment, you cannot process logs sequentially. You need a distributed message broker.

We use **Redpanda** (a Kafka-compatible C++ broker).

* **Topic**: A categorized stream of data.
* **Partition**: Splits a topic to allow parallel processing.
* **Consumer Group**: Allows multiple backend workers to read from the same topic simultaneously without duplicating work.
    """)

    write_file("docs/05_architecture/redis_entity.md", """
# Redis Entity Behavior

## Bounded State
Stateless processing is impossible for behavioral detection. A port scan takes time. A beacon takes time. 
However, storing indefinite state in RAM causes Out Of Memory (OOM) crashes.

We use **Redis** to maintain host behavioral baselines with strict Time-To-Live (TTL) expirations. If a host isn't seen for 5 minutes, its baseline gracefully expires.
    """)

    write_file("docs/05_architecture/window_manager.md", """
# The Window Manager

## Tumbling Windows
Network traffic is infinite. We chunk it into finite 10-second blocks called **Tumbling Windows**.

Every 10 seconds, the window flushes its contents into the Feature Engine and ML model, then resets.

## Trade-offs
This guarantees low latency and memory safety, but creates a blind spot for extremely slow behaviors (like the T11 Slow Scan), which purposefully send packets minutes apart to evade window boundaries.
    """)

    write_file("docs/05_architecture/soc_dashboard.md", """
# SOC Dashboard

## Anatomy of the SOC
Our frontend is a React-based Single Page Application connected via WebSockets.

* **Health**: Live metrics of Redpanda, Redis, and ML stages.
* **Timeline**: Real-time incoming observations.
* **Security Cases**: The fused output.

A Security Case provides an analyst with:
1. Threat Class (e.g., DDoS)
2. Severity & Confidence
3. Cryptographic Model Version (e.g., `v5-prod`)
4. Raw Evidence Matrix
    """)

if __name__ == "__main__":
    build_part3()
    print("Part 3 Generated!")
