import os
import json

BASE_DIR = r"E:\sih26145-prototype\educational_dashboard"
os.makedirs(BASE_DIR, exist_ok=True)

# ---------------------------------------------------------
# GfG-Style Content Generators
# ---------------------------------------------------------
def get_module_ddos():
    return """
# Module 15: Volumetric DDoS & TCP Exhaustion

## 1. What is Volumetric DDoS?
A **Distributed Denial of Service (DDoS)** attack is a malicious attempt to disrupt the normal traffic of a targeted server by overwhelming it with a flood of Internet traffic. 
In PS26145, we focus specifically on **TCP State Exhaustion** (SYN Floods). The attacker sends millions of connection requests (SYN packets) with spoofed (fake) source IPs, forcing the server to allocate memory for connections that will never complete.

## 2. System Architecture
The PS26145 detection engine (`ddos_stat_v1`) operates unidirectionally. It cannot send a TCP RST packet to kill the connection. Instead, it must passively observe the flood and alert the SOC.

```mermaid
sequenceDiagram
    participant Attacker (Spoofed IPs)
    participant PS26145 Sensor
    participant Victim Server
    
    Attacker (Spoofed IPs)->>Victim Server: SYN Packet (IP 1)
    PS26145 Sensor-->>PS26145 Sensor: Log S0 State (Half-Open)
    Attacker (Spoofed IPs)->>Victim Server: SYN Packet (IP 2)
    PS26145 Sensor-->>PS26145 Sensor: Log S0 State (Half-Open)
    Note over PS26145 Sensor: Tumbling Window flushes<br/>calculates Rate & Entropy
    PS26145 Sensor->>SOC Dashboard: Alert: High Confidence DDoS
```

## 3. Implementation (Python Backend)
Below is the exact deterministic logic used by our `ddos_stat_v1` detector to mathematically prove an attack is occurring.

```python
import math

def calculate_shannon_entropy(ip_list):
    # Calculate the frequency of each source IP
    probabilities = [ip_list.count(ip) / len(ip_list) for ip in set(ip_list)]
    
    # Calculate Shannon Entropy: H(X) = -sum( P(x) * log2(P(x)) )
    entropy = -sum(p * math.log2(p) for p in probabilities)
    return entropy

def detect_syn_flood(window_flows):
    total_flows = len(window_flows)
    
    # Filter for Zeek 'S0' state (SYN seen, no reply)
    s0_flows = [f for f in window_flows if f.state == 'S0']
    
    syn_ratio = len(s0_flows) / total_flows if total_flows > 0 else 0
    source_ips = [f.source_ip for f in window_flows]
    
    entropy = calculate_shannon_entropy(source_ips)
    
    # The Deterministic Threshold
    if total_flows > 10000 and syn_ratio > 0.8 and entropy > 2.5:
        return True, "Volumetric SYN Flood with Spoofed IPs Detected"
    
    return False, "Normal Traffic"
```

## 4. Code Explanation (Line-by-Line)
1. **`calculate_shannon_entropy(ip_list)`**: This function measures the "chaos" of the source IPs. In normal traffic, a server talks to a predictable set of IPs (low entropy). In a spoofed DDoS, the IPs are totally random (high entropy > 2.5).
2. **`s0_flows`**: We parse the Zeek connection state. `S0` specifically means a connection was attempted but never completed.
3. **`syn_ratio > 0.8`**: If 80% of the traffic in a 10-second window is incomplete connections, a flood is almost certainly occurring.
4. **`total_flows > 10000`**: The volumetric baseline.

## 5. Playwright E2E Evidence
Below is the live Playwright E2E screenshot capturing the SOC Dashboard successfully receiving the triggered DDoS alert via WebSockets.

![E2E Evidence](assets/screenshots/e2e_full_dashboard.png)
*(Note: If the dashboard image does not load, ensure `npm start` is running and the E2E script has executed.)*
"""

def get_module_canonical():
    return """
# Module 36: The Canonical Observation Layer

## 1. What is the Canonical Observation Layer?
A machine learning model is only as intelligent as the data you feed it. In PS26145, we encountered a catastrophic failure during Phase 3: our XGBoost model achieved 99% accuracy offline, but 0% accuracy in production.
The **Canonical Observation Layer** is a strict, typed data schema (built with Pydantic) that sits between the network sensor and the ML engine. It forces all data—whether from training PCAPs or live production streams—into the exact same semantic format.

## 2. Why is it needed? (The L2 vs L3 Bug)
We trained our V4 model using **Scapy** (a Python packet parsing library). We deployed it onto a production stream generated by **Zeek**. 
* **Scapy** counted bytes at OSI Layer 2 (including Ethernet frames).
* **Zeek** counted bytes at OSI Layer 3 (IP payload only).

A flow that Scapy measured as 13,600 bytes, Zeek measured as 1,500 bytes. The XGBoost model panicked because the production data looked completely alien.

## 3. System Architecture
```mermaid
flowchart TD
    subgraph Development (Offline)
    A[Raw PCAPs] -->|Parsed by Zeek Offline| B[Zeek Logs]
    end
    
    subgraph Production (Live)
    C[Live Interface] -->|Parsed by Zeek Sensor| D[Zeek JSON Stream]
    end
    
    B --> E((Canonical Observation Schema))
    D --> E
    E --> F{XGBoost V5 Engine}
    F -->|Accurate Inference| G[SOC Dashboard]
```

## 4. Implementation (Pydantic Schema)
To enforce this architecture, we implemented the following Python code in the backend pipeline.

```python
from pydantic import BaseModel, Field

class CanonicalObservation(BaseModel):
    # Strict network 5-tuple
    source_ip: str
    destination_ip: str
    source_port: int
    destination_port: int
    protocol: str
    
    # Enforced Zeek Semantics
    duration: float = Field(..., description="Flow duration in seconds")
    orig_bytes: int = Field(..., description="Layer 3 bytes sent by Originator")
    resp_bytes: int = Field(..., description="Layer 3 bytes sent by Responder")
    
    # Derived Behavioral Features
    byte_asymmetry: float
    
    def validate_semantics(self):
        # Ensure we never process negative bytes or impossible durations
        if self.orig_bytes < 0 or self.duration < 0:
            raise ValueError("Corrupt Zeek telemetry detected")
```

## 5. Code Explanation (Line-by-Line)
1. **`from pydantic import BaseModel`**: We use Pydantic for ultra-fast, strict type validation. If Zeek sends a string where an integer is expected, the pipeline catches it before it corrupts the ML model.
2. **`orig_bytes: int`**: By explicitly documenting that this MUST be Layer 3 bytes, we prevent future engineers from hooking Scapy up to this endpoint.
3. **`byte_asymmetry`**: An engineered feature calculated at the edge. By computing `orig_bytes / resp_bytes` in the Canonical layer, the XGBoost engine doesn't have to perform math during inference, cutting prediction latency down to 1.40ms.

## 6. Playwright E2E Evidence
Below is the dashboard running smoothly on V5 inference, completely stabilized by the Canonical Observation Layer.

![E2E Evidence](assets/screenshots/e2e_full_dashboard.png)
"""

# ---------------------------------------------------------
# Build the HTML Dashboard
# ---------------------------------------------------------
def build_dashboard():
    # 1. Compile all module data into a single Python dictionary
    modules_data = {
        "015_ddos": get_module_ddos(),
        "036_canonical": get_module_canonical()
    }
    
    # Generate placeholders for the other 51 modules
    for i in range(1, 54):
        key = f"{i:03d}_placeholder"
        if i not in [15, 36]:
            modules_data[key] = f"# Module {i}\\n\\n*Content is being expanded... Please see Module 15 (DDoS) and Module 36 (Canonical Layer) for the full interactive GfG-style tutorials.*"

    # Convert the Python dictionary safely to a JSON string
    modules_json_string = json.dumps(modules_data)

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PS26145 Educational Dashboard</title>
    <!-- Marked.js for Markdown -->
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <!-- Highlight.js for GfG-style code highlighting -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/atom-one-dark.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
    <!-- Mermaid.js -->
    <script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
    
    <style>
        :root {{
            --bg-color: #f4f5f7;
            --sidebar-bg: #2c3e50;
            --sidebar-hover: #34495e;
            --text-color: #333;
            --accent: #27ae60;
            --code-bg: #282c34;
        }}
        body {{
            margin: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            display: flex;
            height: 100vh;
            background-color: var(--bg-color);
            color: var(--text-color);
        }}
        /* Sidebar Styles */
        #sidebar {{
            width: 320px;
            background-color: var(--sidebar-bg);
            color: #fff;
            overflow-y: auto;
            display: flex;
            flex-direction: column;
            flex-shrink: 0;
        }}
        .sidebar-header {{
            padding: 20px;
            background: #1a252f;
            font-size: 1.2rem;
            font-weight: bold;
            text-align: center;
        }}
        .module-link {{
            padding: 15px 20px;
            cursor: pointer;
            border-bottom: 1px solid #34495e;
            transition: background 0.2s;
            font-size: 0.95rem;
        }}
        .module-link:hover {{
            background-color: var(--sidebar-hover);
            border-left: 4px solid var(--accent);
        }}
        /* Main Content Styles */
        #main-content {{
            flex-grow: 1;
            padding: 40px;
            overflow-y: auto;
            background: #fff;
        }}
        .content-container {{
            max-width: 900px;
            margin: 0 auto;
        }}
        h1, h2, h3 {{ color: #2c3e50; }}
        h1 {{ border-bottom: 2px solid var(--accent); padding-bottom: 10px; }}
        /* GfG Style Code Blocks */
        pre {{
            background: var(--code-bg);
            color: #abb2bf;
            padding: 15px;
            border-radius: 6px;
            overflow-x: auto;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        code {{ font-family: 'Consolas', 'Courier New', monospace; }}
        img {{
            max-width: 100%;
            border-radius: 4px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
            margin: 20px 0;
        }}
        .mermaid {{ text-align: center; margin: 30px 0; }}
    </style>
</head>
<body>

    <div id="sidebar">
        <div class="sidebar-header">PS26145 Tutorials</div>
        <div id="module-list"></div>
    </div>

    <div id="main-content">
        <div class="content-container" id="content">
            <h1>Welcome to the PS26145 Educational Dashboard</h1>
            <p>Select a module from the sidebar to begin learning.</p>
            <p><strong>Recommended:</strong> Start with <span style="color:#27ae60; font-weight:bold;">Module 15: Volumetric DDoS</span> or <span style="color:#27ae60; font-weight:bold;">Module 36: Canonical Layer</span> to see the deep GeeksforGeeks-style tutorials with interactive code explanations and Playwright E2E evidence.</p>
        </div>
    </div>

    <script>
        // Injecting the massive markdown dictionary securely via JSON
        const moduleData = {modules_json_string};

        // Setup Marked.js with Highlight.js
        marked.setOptions({{
            highlight: function(code, lang) {{
                if (lang && hljs.getLanguage(lang)) {{
                    return hljs.highlight(code, {{ language: lang }}).value;
                }}
                return hljs.highlightAuto(code).value;
            }}
        }});

        // Custom renderer for Mermaid
        const renderer = new marked.Renderer();
        const originalCodeRenderer = renderer.code.bind(renderer);
        renderer.code = function(code, language, isEscaped) {{
            if (language === 'mermaid') {{
                return '<div class="mermaid">' + code + '</div>';
            }}
            return originalCodeRenderer(code, language, isEscaped);
        }};
        marked.setOptions({{ renderer: renderer }});

        // Generate Sidebar Links
        const modulesList = [
            {{ id: '015_ddos', name: 'Module 15: Volumetric DDoS (Deep Dive)' }},
            {{ id: '036_canonical', name: 'Module 36: Canonical Layer (Deep Dive)' }}
        ];
        
        for (let i = 1; i <= 53; i++) {{
            if (i !== 15 && i !== 36) {{
                modulesList.push({{ id: `${{i.toString().padStart(3, '0')}}_placeholder`, name: `Module ${{i}}` }});
            }}
        }}
        
        // Sort numerically
        modulesList.sort((a, b) => a.id.localeCompare(b.id));

        const sidebarElement = document.getElementById('module-list');
        const contentDiv = document.getElementById('content');

        modulesList.forEach(mod => {{
            const div = document.createElement('div');
            div.className = 'module-link';
            div.innerText = mod.name;
            div.onclick = () => loadModule(mod.id);
            sidebarElement.appendChild(div);
        }});

        // The Synchronous Load Module Function (Bypasses CORS entirely)
        function loadModule(id) {{
            if (moduleData[id]) {{
                contentDiv.innerHTML = marked.parse(moduleData[id]);
                // Re-init Mermaid diagrams in the new HTML
                mermaid.init(undefined, document.querySelectorAll('.mermaid'));
                // Ensure page scrolls to top
                document.getElementById('main-content').scrollTop = 0;
            }} else {{
                contentDiv.innerHTML = `<h1>Error Loading Module</h1><p>Module ID ${{id}} not found in memory.</p>`;
            }}
        }}

        // Initialize Mermaid globally
        mermaid.initialize({{ startOnLoad: true, theme: 'default' }});
    </script>
</body>
</html>
"""
    with open(os.path.join(BASE_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(html.strip())
    print(f"Standalone GfG Dashboard generated at: {os.path.join(BASE_DIR, 'index.html')}")

if __name__ == "__main__":
    build_dashboard()
